AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Resources:
  MyCrudFunction:
    Type: AWS::Serverless::Function
    Properties:
      Handler: app.lambda_handler
      Runtime: python3.8
      CodeUri: .
      Events:
        CreateEvent:
          Type: Api
          Properties:
            Path: /create
            Method: post
        ReadEvent:
          Type: Api
          Properties:
            Path: /read/{id}
            Method: get
        UpdateEvent:
          Type: Api
          Properties:
            Path: /update/{id}
            Method: put
        DeleteEvent:
          Type: Api
          Properties:
            Path: /delete/{id}
            Method: delete